// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


    static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBk9uUFL-csq5kkftUvz7Ijons7gbC5vkg",
  authDomain: "dietchat-2f3a8.firebaseapp.com",
  projectId: "dietchat-2f3a8",
  storageBucket: "dietchat-2f3a8.appspot.com",
  messagingSenderId: "498712831877",
  appId: "1:498712831877:web:5c1eb6f6000013a33286ec"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi8QNmfAliV9ChQg2I03PBDjTAVi3x2Mg',
    appId: '1:498712831877:android:77334d5709371ca63286ec',
    messagingSenderId: '498712831877',
    projectId: 'dietchat-2f3a8',
    storageBucket: 'dietchat-2f3a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAry59ZZIWJG3BU7TT3toV4gxzKkEvG8lk',
    appId: '1:498712831877:ios:6a224dea8644d5293286ec',
    messagingSenderId: '498712831877',
    projectId: 'dietchat-2f3a8',
    storageBucket: 'dietchat-2f3a8.appspot.com',
    iosBundleId: 'com.example.gp',
  );
}